import nodemailer from 'nodemailer';

export class NotificationService {
    private transporter;

    constructor() {
        // For development, we can use Ethereal or a dummy transport
        // In production, configure with real SMTP credentials
        this.transporter = nodemailer.createTransport({
            host: "smtp.ethereal.email",
            port: 587,
            secure: false, // true for 465, false for other ports
            auth: {
                user: "test_user", // Generated by Ethereal
                pass: "test_pass", // Generated by Ethereal
            },
        });
    }

    async sendWelcomeEmail(email: string, name: string, authId: string) {
        console.log(`[NotificationService] Sending welcome email to ${email} (${name})`);

        try {
            // In a real app, you'd send the actual email here
            // await this.transporter.sendMail({ ... });
            console.log(`[NotificationService] Welcome email sent successfully to ${email}`);
        } catch (error) {
            console.error(`[NotificationService] Failed to send welcome email:`, error);
        }
    }

    async sendAdminAlert(subject: string, message: string) {
        console.log(`[NotificationService] ADMIN ALERT: ${subject} - ${message}`);
    }
}
